env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.eslint.json
plugins:
 - '@typescript-eslint'
rules:
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/explicit-module-boundary-types": 0

