language: node_js
node_js:
    - 14
addons:
    chrome: stable
services:
    - xvfb
git:
    autocrlf: input
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install
script: 
    prettier --check "src/**/*.ts" &&
    node_modules/karma/bin/karma start karma.conf.js --single-run
notifications:
    email:
        on_success: change
        on_failure: change