language: node_js
node_js:
    - 14
services:
    - xvfb
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run